package claudemd

import (
	"fmt"
	"sort"
	"strings"

	"github.com/zzet/gortex/internal/graph"
	"github.com/zzet/gortex/internal/query"
)

// Generate produces a CLAUDE.md block describing the indexed codebase and how to use Gortex tools.
func Generate(engine *query.Engine, maxLines int) string {
	if maxLines <= 0 {
		maxLines = 180
	}

	stats := engine.Stats()
	var b strings.Builder

	b.WriteString("## Codebase Overview (generated by Gortex)\n\n")

	// Language breakdown.
	langs := sortedKeys(stats.ByLanguage)
	if len(langs) > 0 {
		primary := langs[0]
		for _, l := range langs {
			if stats.ByLanguage[l] > stats.ByLanguage[primary] {
				primary = l
			}
		}
		langParts := make([]string, 0, len(langs))
		for _, l := range langs {
			if l == primary {
				langParts = append([]string{fmt.Sprintf("%s (primary)", l)}, langParts...)
			} else {
				langParts = append(langParts, l)
			}
		}
		b.WriteString(fmt.Sprintf("- **Languages:** %s\n", strings.Join(langParts, ", ")))
	}

	// Entry points (main functions).
	entryPoints := engine.FindSymbols("main", graph.KindFunction)
	if len(entryPoints) > 0 {
		paths := make([]string, 0, len(entryPoints))
		for _, ep := range entryPoints {
			paths = append(paths, fmt.Sprintf("`%s`", ep.FilePath))
		}
		b.WriteString(fmt.Sprintf("- **Entry points:** %s\n", strings.Join(paths, ", ")))
	}

	// Key symbols (most referenced).
	topSymbols := findMostReferenced(engine, 10)
	if len(topSymbols) > 0 {
		parts := make([]string, 0, len(topSymbols))
		for _, s := range topSymbols {
			parts = append(parts, fmt.Sprintf("`%s` (%d usages)", s.name, s.count))
		}
		b.WriteString(fmt.Sprintf("- **Most-referenced symbols:** %s\n", strings.Join(parts, ", ")))
	}

	b.WriteString(fmt.Sprintf("- **Graph size:** %d nodes, %d edges\n", stats.TotalNodes, stats.TotalEdges))

	// Kind breakdown.
	if len(stats.ByKind) > 0 {
		parts := make([]string, 0, len(stats.ByKind))
		for _, k := range sortedKeys(stats.ByKind) {
			parts = append(parts, fmt.Sprintf("%d %ss", stats.ByKind[k], k))
		}
		b.WriteString(fmt.Sprintf("- **Breakdown:** %s\n", strings.Join(parts, ", ")))
	}

	b.WriteString("\n## Working with this codebase (Gortex tools available)\n\n")
	b.WriteString("Gortex is running as an MCP server. Prefer graph queries over file reads:\n\n")
	b.WriteString("| Instead of... | Use... |\n")
	b.WriteString("|---|---|\n")
	b.WriteString("| Reading a file to find a function | `get_symbol` or `get_editing_context` |\n")
	b.WriteString("| Grep for all references | `find_usages` |\n")
	b.WriteString("| Reading multiple files to trace a call | `get_call_chain` / `get_callers` |\n")
	b.WriteString("| Guessing an import path | `find_import_path` |\n")
	b.WriteString("| Assessing change scope | `explain_change_impact` |\n\n")

	b.WriteString("**Workflow:** Before editing any file, call `get_editing_context(\"<file>\")` first.\n")
	b.WriteString("Before any refactor affecting a shared type or function, call `explain_change_impact`.\n\n")

	b.WriteString("## Session start (Gortex)\n")
	b.WriteString("1. Call `graph_stats` to confirm Gortex is running and get repo orientation.\n")
	b.WriteString("2. If `total_nodes` is 0, call `index_repository` with path \".\".\n")
	b.WriteString("3. For every file you are about to edit, call `get_editing_context` first.\n")

	return b.String()
}

type symbolRef struct {
	name  string
	count int
}

func findMostReferenced(engine *query.Engine, limit int) []symbolRef {
	allNodes := engine.AllNodes()
	relevantKinds := map[graph.EdgeKind]bool{
		graph.EdgeCalls:        true,
		graph.EdgeReferences:   true,
		graph.EdgeInstantiates: true,
		graph.EdgeImplements:   true,
	}

	var refs []symbolRef
	for _, n := range allNodes {
		if n.Kind == graph.KindFile || n.Kind == graph.KindImport {
			continue
		}
		count := 0
		for _, e := range engine.GetInEdges(n.ID) {
			if relevantKinds[e.Kind] {
				count++
			}
		}
		if count > 0 {
			refs = append(refs, symbolRef{name: n.Name, count: count})
		}
	}

	sort.Slice(refs, func(i, j int) bool {
		return refs[i].count > refs[j].count
	})

	if len(refs) > limit {
		refs = refs[:limit]
	}
	return refs
}

func sortedKeys(m map[string]int) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
